#!/bin/bash

cd /tmp

rm -r /tmp/iznik.recent
mkdir iznik.recent
cd iznik.recent
git clone https://github.com/Freegle/iznik-client.git
cd iznik-client
git log --pretty=format:'%s (%cr)' --abbrev-commit --since="7 days ago" > /tmp/git.log
printf "This is an automated list of the changes to the client code in the last 7 days.  If you have any questions about them, please reply to this mail.\n\nHere are the more important ones which would affect members:\n\n" > /tmp/git.mail
grep "^*" /tmp/git.log >> /tmp/git.mail
printf "\n...and here are the ones which are minor, or only affect volunteers in ModTools, or are internal changes that you wouldn't notice:\n\n"  >> /tmp/git.mail
grep -v "^*" /tmp/git.log >> /tmp/git.mail
cat /tmp/git.mail | mail -s "Client code changes in the last 7 days" "Freegle-Tech@yahoogroups.com" -aFrom:geeks@ilovefreegle.org
rm /tmp/git.mail
cd /tmp

rm -r /tmp/iznik.recent
mkdir iznik.recent
cd iznik.recent
git clone https://github.com/Freegle/iznik-server.git
cd iznik-server
git log --pretty=format:'%s (%cr)' --abbrev-commit --since="7 days ago" > /tmp/git.log
printf "This is an automated list of the changes to the server code in the last 7 days.  If you have any questions about them, please reply to this mail.\n\nHere are the more important ones which would affect members:\n\n" > /tmp/git.mail
grep "^*" /tmp/git.log >> /tmp/git.mail
printf "\n...and here are the ones which are minor, or only affect volunteers in ModTools, or are internal changes that you wouldn't notice:\n\n"  >> /tmp/git.mail
grep -v "^*" /tmp/git.log >> /tmp/git.mail
cat /tmp/git.mail | mail -s "Server code changes in the last 7 days" "Freegle-Tech@yahoogroups.com" -aFrom:geeks@ilovefreegle.org
rm /tmp/git.mail
cd /tmp

rm -r /tmp/iznik.recent
mkdir iznik.recent
cd iznik.recent
git clone https://github.com/Freegle/iznik-nuxt.git
cd iznik-nuxt
git log --pretty=format:'%s (%cr)' --abbrev-commit --since="7 days ago" > /tmp/git.log
printf "This is an automated list of the changes to the new client code in the last 7 days.  If you have any questions about them, please reply to this mail.\n\nHere are the more important ones which would affect members:\n\n" > /tmp/git.mail
grep "^*" /tmp/git.log >> /tmp/git.mail
printf "\n...and here are the ones which are minor, or only affect volunteers in ModTools, or are internal changes that you wouldn't notice:\n\n"  >> /tmp/git.mail
grep -v "^*" /tmp/git.log >> /tmp/git.mail
cat /tmp/git.mail | mail -s "New version of client (not live yet) code changes in the last 7 days" "Freegle-Tech@yahoogroups.com" -aFrom:geeks@ilovefreegle.org
rm /tmp/git.mail
cd /tmp

rm -r iznik.recent