#!/bin/bash
cd /var/www/iznik/scripts/incoming
if [[ "$RECIPIENT" =~ "readreceipt-" ]]; then
    php incoming.php >> /tmp/iznik_incoming.out 2>&1
else
    php bounce.php >> /tmp/iznik_bounce.out 2>&1
fi
