#!/bin/bash
EMAIL=geek-alerts@ilovefreegle.org

XTRABACKUP=/usr/bin/xtrabackup

# User and password are in [xtrabackup] in ~/.my.cnf
OPTIONS="--backup --stream=xbstream --target-dir=/backup --compress --compress-threads=4"
BACKUP="$XTRABACKUP $OPTIONS $BACKUPDIR"

timestamp=$(date +%Y-%m-%d-%H-%M)

pgrep mysql
if [ $? == 0 ]; then
    # Desync from the cluster.  This stops our backup adversely affecting the rest of the cluster - we've seen
    # cases where requests get blocked on other nodes while the backup is occurring.
    mysql --execute "SET GLOBAL wsrep_desync = ON"

    # We back up to Google storage, and this is then used by the yesterday system.
    $BACKUP | /usr/lib/google-cloud-sdk/platform/gsutil/gsutil cp - gs://freegle_backup_uk/iznik-$timestamp.xbstream > /tmp/gsutil.out 2>&1

    if [ $? == 0 ]; then
      grep "Operation completed" /tmp/gsutil.out
      if [ $? == 0 ]; then
        cat /tmp/gsutil.out | mail -s "BACKUP SUCCESS: MySQL backed up to $BACKUPDIR/$MOST_RECENT" $EMAIL
      else
        cat /tmp/gsutil.out | mail -s "BACKUP ERROR: MySQL backup didn't work" $EMAIL
      fi
    else
       # problem with initial backup :(
       echo "Couldn't do a mysql backup" | mail -s "BACKUP ERROR: MySQL backup failed" $EMAIL
    fi

    mysql --execute "SET GLOBAL wsrep_desync = OFF"
else
    echo "MySQL not running"| mail -s "BACKUP ERROR: MySQL not running" $EMAIL
fi

# Back up /etc
rm -r /tmp/etcback
mkdir /tmp/etcback
cd /tmp/etcback
for host in app1-internal bulk2-internal bulk3-internal bulk4-internal db1-internal db2-internal db3-internal app1 app4 freeglecdnsov freeglecdnhex tiles ha-internal
do
    ssh $host "(cd /etc; tar -cvzf - ./)" > $host.etc.tgz
    ssh $host "(cd /var/spool/cron; tar -cvzf - ./)" > $host.crontab.tgz
done
tar -cvf iznik-etc-$timestamp.tgz ./
/usr/lib/google-cloud-sdk/platform/gsutil/gsutil cp iznik-etc-$timestamp.tgz gs://freegle_backup_uk/ >> /tmp/gsutil.out 2>&1
echo "Backup complete"
